---
  #################################
  #################################
  ## Super Linter GitHub Actions ##
  #################################
  #################################
  name: Lint Code Base
  
  #############################
  # Start the job on all push #
  #############################
  on:
    push:
      branches-ignore: [master, main]
      # Remove the line above to run when pushing to master or main
    pull_request:
      branches: [master, main]
  
  ###############
  # Set the Job #
  ###############
  jobs:
    build:
      # Name the Job
      name: Lint Code Base
      # Set the agent to run on
      runs-on: ubuntu-latest
  
      ############################################
      # Grant status permission for MULTI_STATUS #
      ############################################
      permissions:
        contents: read
        packages: read
        statuses: write
  
      ##################
      # Load all steps #
      ##################
      steps:
        
        - name: Clean Workspace
          uses: AutoModality/action-clean@v1.1.0
        
        ##########################
        # Checkout the code base #
        ##########################
        - name: Checkout Code
          uses: actions/checkout@v4
          with:
            # Full git history is needed to get a proper
            # list of changed files within `super-linter`
            fetch-depth: 0
  
        ################################
        # Run Linter against code base #
        ################################
        - name: Lint Code Base
          uses: super-linter/super-linter@v5
          env:
            VALIDATE_ALL_CODEBASE: false
            VALIDATE_DOCKERFILE_HADOLINT: true
            VALIDATE_PYTHON_FLAKE8: true
            VALIDATE_PYTHON_ISORT: true
            VALIDATE_BASH: true
            VALIDATE_HTML: true
            VALIDATE_JSON: true
            VALIDATE_JAVASCRIPT: true
            VALIDATE_MARKDOWN: true
            DEFAULT_BRANCH: main

  